base:
  seed: 1111
  batch_size: 200
  num_workers: 0
  num_layers: 1
  attn_dropout: 0.5
  train_mode: regression # only support regression now
  key_eval: Non0_acc_2 # Has0_acc_2
  type: test #
  missing_rate_eval_test: 0   # used for evaluation and testing


dataset:
  datasetName: mosi
  dataPath: ../data/MSA_Datasets/MOSI/Processed/unaligned_50.pkl
   

model:    
  feature_extractor:
    bert_pretrained: '../bert/bert-base-uncased' #    bert_pretrained: '../bert/bert-large-uncased'
    transformers: 'bert'  # transformers: bert
    input_length: [50, 500, 375] # language, video, audio
    token_length: [8, 8, 8] # language, video, audio
    heads: 8
    input_dims: [768, 20, 5] # language, video, audio
    hidden_dims: [128, 128, 128] # language, video, audio
    depth: 2

  moe:
    dim: 128
    heads: 8
    dim_head: 128
    num_experts: 4
    top_k: 3
    capacity_factor: 1.0
    dropout: 0.1

  gated_fusion:
    hidden_dims: 128

  crossmodal_encoder:
    hidden_dims: [128, 128, 128] # language, video, audio
    embed_dim: 128
    num_layers: 1
    attn_dropout: 0.5

  regression:
    attn_dropout: 0.5
    input_dim: 128
    hidden_dim: 128
    out_dim: 1
